spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require}
    username: ${DB_USERNAME:postgres.bwlqcyapewflawzafusn}
    password: ${DB_PASSWORD:supasupaAish98*}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: ${DB_INIT_MODE:never}